include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    overridden_fields: ignore
    camel_case_types: ignore
    use_super_parameters: ignore
    implementation_imports: ignore
    avoid_redundant_argument_values: ignore
    invalid_use_of_visible_for_testing_member: ignore
    prefer_const_constructors: ignore
    non_constant_identifier_names: ignore
    prefer_const_literals_to_create_immutables: ignore

linter:
  rules:
    no_leading_underscores_for_library_prefixes: false
